### PR TITLE
Workaround for multiple parameters in the output modules

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
What is this?
ConfdDB v2? The new GUI? Something else?????????????

**Comment by fwyzard** [comment]
It's the new web-based GUI that Vincenzo is developing.
I'll let him handle the patches :-)

**Comment by Martin-Grunewald** [comment]
OK! Does/will it work with ConfDB v2?
Also, there was not any update on this effort for a very long time :(

**Comment by fwyzard** [comment]
Actually, this works *only* with ConfDB v2 .

Good point, I'll ask Vincenzo to give a report next week, or the following one.

.A

**Comment by fwyzard** [comment]
this is included in 1.2.5

**Pull request closed without merging**
